# Generated by Django 5.1.1 on 2024-09-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'livro'},
        ),
    ]
